### ISSUE TITLE
Dockerize 'scripts/iothub' tools

### ISSUE THREAD

**Issue by dluc** [Azure/iothub-manager-java#3]
Clone of https://github.com/Azure/iothub-manager-dotnet/issues/27

# Type of issue
- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description
Allow to use the scripts under `scripts/iothub` from any console, without the need to setup the OS, other than Docker

**Comment by ppathan** [comment]
@dluc Do we still need this? Can you open an item in TFS
