### ISSUE TITLE
Refactor Caching to place it in IotHubManager

### ISSUE THREAD

**Issue by timlaverty** [Azure/iothub-manager-java#73]
# Type of issue 

- [x ] Bug
- [x ] New feature
- [x ] Enhancement

# Description 
Right now caching is owned by PCS-Config.  This is designed poorly; i.e. the hubmanager should "own" caching itself b/c all of the data being cached is hub related device data.  We should move the caching logic to this service.

**Comment by molly-moen** [comment]
Work done by @isaac73
