### ISSUE TITLE
Unable to create physical device

### ISSUE THREAD

**Issue by zhang-hua** [Azure/iothub-manager-java#83]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

Unable to create physical device and failed with NullPointerException.

# Steps to reproduce 

1. [First step] Add new device
2. [Second step] select physical device with enable ”System generated device IDs“ option
3. [and so on...] Apply

# Current behavior <!-- The actual behavior observed --

POST　/iothubmanager/v1/devices
{"Id":"","Authentication":{},"IsSimulated":false}

500 Internal Server Error

{
  "ExceptionType": "java.lang.NullPointerException",
  "ExceptionMessage": null,
  "Message": "An error has occurred",
  "StackTrace": [
    {
      "methodName": "toAzureModel",
      "fileName": "AuthenticationType.java",
      "lineNumber": 22,
      "className": "com.microsoft.azure.iotsolutions.iothubmanager.services.models.AuthenticationType",
      "nativeMethod": false
    },
    {
      "methodName": "<init>",
      "fileName": "AuthenticationMechanismServiceModel.java",
      "lineNumber": 17,
      "className": "com.microsoft.azure.iotsolutions.iothubmanager.services.models.AuthenticationMechanismServiceModel",
      "nativeMethod": false
    },
    {
      "methodName": "toServiceModel",
      "fileName": "AuthenticationMechanismApiModel.java",
      "lineNumber": 80,
      "className": "com.microsoft.azure.iotsolutions.iothubmanager.webservice.v1.models.AuthenticationMechanismApiModel",
      "nativeMethod": false
    },
    {
      "methodName": "toServiceModel",
      "fileName": "DeviceRegistryApiModel.java",
      "lineNumber": 195,
      "className": "com.microsoft.azure.iotsolutions.iothubmanager.webservice.v1.models.DeviceRegistryApiModel",
      "nativeMethod": false
    },
    {
      "methodName": "postAsync",
      "fileName": "DevicesController.java",
      "lineNumber": 63,
      "className": "com.microsoft.azure.iotsolutions.iothubmanager.webservice.v1.controllers.DevicesController",
      "nativeMethod": false
    },
    {
      "methodName": "$anonfun$applyOrElse$12",
      "fileName": "Routes.scala",
      "lineNumber": 394,
      "className": "router.Routes$$anonfun$routes$1",
      "nativeMethod": false
    },
    {
      "methodName": "resultCall",
      "fileName": "HandlerInvoker.scala",
      "lineNumber": 137,
      "className": "play.core.routing.HandlerInvokerFactory$$anon$4",
      "nativeMethod": false
    },
    {
      "methodName": "invocation",
      "fileName": "HandlerInvoker.scala",
      "lineNumber": 108,
      "className": "play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1",
      "nativeMethod": false
    },
    {
      "methodName": "call",
      "fileName": "JavaAction.scala",
      "lineNumber": 76,
      "className": "play.core.j.JavaAction$$anon$1",
      "nativeMethod": false
    },
    {
      "methodName": "call",
      "fileName": "DefaultActionCreator.java",
      "lineNumber": 31,
      "className": "play.http.DefaultActionCreator$1",
      "nativeMethod": false
    },
    {
      "methodName": "$anonfun$apply$2",
      "fileName": "JavaAction.scala",
      "lineNumber": 111,
      "className": "play.core.j.JavaAction",
      "nativeMethod": false
    },
    {
      "methodName": "$anonfun$apply$1",
      "fileName": "Future.scala",
      "lineNumber": 655,
      "className": "scala.concurrent.Future$",
      "nativeMethod": false
    },
    {
      "methodName": "$anonfun$map$1",
      "fileName": "Try.scala",
      "lineNumber": 251,
      "className": "scala.util.Success",
      "nativeMethod": false
    },
    {
      "methodName": "map",
      "fileName": "Try.scala",
      "lineNumber": 209,
      "className": "scala.util.Success",
      "nativeMethod": false
    },
    {
      "methodName": "$anonfun$map$1",
      "fileName": "Future.scala",
      "lineNumber": 289,
      "className": "scala.concurrent.Future",
      "nativeMethod": false
    },
    {
      "methodName": "liftedTree1$1",
      "fileName": "Promise.scala",
      "lineNumber": 29,
      "className": "scala.concurrent.impl.Promise",
      "nativeMethod": false
    },
    {
      "methodName": "$anonfun$transform$1",
      "fileName": "Promise.scala",
      "lineNumber": 29,
      "className": "scala.concurrent.impl.Promise",
      "nativeMethod": false
    },
    {
      "methodName": "run",
      "fileName": "Promise.scala",
      "lineNumber": 60,
      "className": "scala.concurrent.impl.CallbackRunnable",
      "nativeMethod": false
    },
    {
      "methodName": "run",
      "fileName": "HttpExecutionContext.scala",
      "lineNumber": 56,
      "className": "play.core.j.HttpExecutionContext$$anon$2",
      "nativeMethod": false
    },
    {
      "methodName": "execute",
      "fileName": "Execution.scala",
      "lineNumber": 70,
      "className": "play.api.libs.streams.Execution$trampoline$",
      "nativeMethod": false
    },
    {
      "methodName": "execute",
      "fileName": "HttpExecutionContext.scala",
      "lineNumber": 48,
      "className": "play.core.j.HttpExecutionContext",
      "nativeMethod": false
    },
    {
      "methodName": "executeWithValue",
      "fileName": "Promise.scala",
      "lineNumber": 68,
      "className": "scala.concurrent.impl.CallbackRunnable",
      "nativeMethod": false
    },
    {
      "methodName": "onComplete",
      "fileName": "Promise.scala",
      "lineNumber": 368,
      "className": "scala.concurrent.impl.Promise$KeptPromise$Kept",
      "nativeMethod": false
    },
    {
      "methodName": "onComplete$",
      "fileName": "Promise.scala",
      "lineNumber": 367,
      "className": "scala.concurrent.impl.Promise$KeptPromise$Kept",
      "nativeMethod": false
    },
    {
      "methodName": "onComplete",
      "fileName": "Promise.scala",
      "lineNumber": 375,
      "className": "scala.concurrent.impl.Promise$KeptPromise$Successful",
      "nativeMethod": false
    },
    {
      "methodName": "transform",
      "fileName": "Promise.scala",
      "lineNumber": 29,
      "className": "scala.concurrent.impl.Promise",
      "nativeMethod": false
    },
    {
      "methodName": "transform$",
      "fileName": "Promise.scala",
      "lineNumber": 27,
      "className": "scala.concurrent.impl.Promise",
      "nativeMethod": false
    },
    {
      "methodName": "transform",
      "fileName": "Promise.scala",
      "lineNumber": 375,
      "className": "scala.concurrent.impl.Promise$KeptPromise$Successful",
      "nativeMethod": false
    },
    {
      "methodName": "map",
      "fileName": "Future.scala",
      "lineNumber": 289,
      "className": "scala.concurrent.Future",
      "nativeMethod": false
    },
    {
      "methodName": "map$",
      "fileName": "Future.scala",
      "lineNumber": 289,
      "className": "scala.concurrent.Future",
      "nativeMethod": false
    },
    {
      "methodName": "map",
      "fileName": "Promise.scala",
      "lineNumber": 375,
      "className": "scala.concurrent.impl.Promise$KeptPromise$Successful",
      "nativeMethod": false
    },
    {
      "methodName": "apply",
      "fileName": "Future.scala",
      "lineNumber": 655,
      "className": "scala.concurrent.Future$",
      "nativeMethod": false
    },
    {
      "methodName": "apply",
      "fileName": "JavaAction.scala",
      "lineNumber": 111,
      "className": "play.core.j.JavaAction",
      "nativeMethod": false
    },
    {
      "methodName": "$anonfun$apply$2",
      "fileName": "Action.scala",
      "lineNumber": 96,
      "className": "play.api.mvc.Action",
      "nativeMethod": false
    },
    {
      "methodName": "$anonfun$flatMap$1",
      "fileName": "Future.scala",
      "lineNumber": 304,
      "className": "scala.concurrent.Future",
      "nativeMethod": false
    },
    {
      "methodName": "$anonfun$transformWith$1",
      "fileName": "Promise.scala",
      "lineNumber": 37,
      "className": "scala.concurrent.impl.Promise",
      "nativeMethod": false
    },
    {
      "methodName": "run",
      "fileName": "Promise.scala",
      "lineNumber": 60,
      "className": "scala.concurrent.impl.CallbackRunnable",
      "nativeMethod": false
    },
    {
      "methodName": "processBatch",
      "fileName": "BatchingExecutor.scala",
      "lineNumber": 55,
      "className": "akka.dispatch.BatchingExecutor$AbstractBatch",
      "nativeMethod": false
    },
    {
      "methodName": "$anonfun$run$1",
      "fileName": "BatchingExecutor.scala",
      "lineNumber": 91,
      "className": "akka.dispatch.BatchingExecutor$BlockableBatch",
      "nativeMethod": false
    },
    {
      "methodName": "apply",
      "fileName": "JFunction0$mcV$sp.java",
      "lineNumber": 12,
      "className": "scala.runtime.java8.JFunction0$mcV$sp",
      "nativeMethod": false
    },
    {
      "methodName": "withBlockContext",
      "fileName": "BlockContext.scala",
      "lineNumber": 81,
      "className": "scala.concurrent.BlockContext$",
      "nativeMethod": false
    },
    {
      "methodName": "run",
      "fileName": "BatchingExecutor.scala",
      "lineNumber": 91,
      "className": "akka.dispatch.BatchingExecutor$BlockableBatch",
      "nativeMethod": false
    },
    {
      "methodName": "run",
      "fileName": "AbstractDispatcher.scala",
      "lineNumber": 40,
      "className": "akka.dispatch.TaskInvocation",
      "nativeMethod": false
    },
    {
      "methodName": "exec",
      "fileName": "ForkJoinExecutorConfigurator.scala",
      "lineNumber": 43,
      "className": "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask",
      "nativeMethod": false
    },
    {
      "methodName": "doExec",
      "fileName": "ForkJoinTask.java",
      "lineNumber": 260,
      "className": "akka.dispatch.forkjoin.ForkJoinTask",
      "nativeMethod": false
    },
    {
      "methodName": "runTask",
      "fileName": "ForkJoinPool.java",
      "lineNumber": 1339,
      "className": "akka.dispatch.forkjoin.ForkJoinPool$WorkQueue",
      "nativeMethod": false
    },
    {
      "methodName": "runWorker",
      "fileName": "ForkJoinPool.java",
      "lineNumber": 1979,
      "className": "akka.dispatch.forkjoin.ForkJoinPool",
      "nativeMethod": false
    },
    {
      "methodName": "run",
      "fileName": "ForkJoinWorkerThread.java",
      "lineNumber": 107,
      "className": "akka.dispatch.forkjoin.ForkJoinWorkerThread",
      "nativeMethod": false
    }
  ]
}

**Comment by ppathan** [comment]
Issue is fixed
