### ISSUE TITLE
IoT Hub Manager in other programming languages

### ISSUE THREAD

**Issue by brunoborges** [Azure/iothub-manager-java#93]
Are there other projects that deliver the same as this one, but implemented in other languages?

**Comment by dluc** [comment]
the same microservice is available in .NET here https://github.com/Azure/iothub-manager-dotnet

were you looking for a language in particular?

**Comment by brunoborges** [comment]
No, thanks. Was just wondering if there was a need to have "-java" in the repo name. Thanks for confirming. that it does :-)

**Comment by brunoborges** [comment]
My followup question is whether it is possible for a Java developer to connect to the iothub-manager implemented in dotnet. If yes, next question is why there is a need to have both.

**Comment by molly-moen** [comment]
You can connect to the IoT Hub Manager implemented in dotnet if all you need is the functionality. The reason we maintain both languages is if you want to customize your solution, you have the option to customize it in java or in dotnet, whichever is most comfortable for you.

**Comment by brunoborges** [comment]
Got it. Thanks!
